# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloneapp', '0006_commentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_text', models.CharField(max_length=555)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloneapp.PostModel')),
            ],
        ),
    ]
